"""empty message

Revision ID: 8bd6b0238a2f
Revises: 838700396f8c
Create Date: 2026-02-02 21:21:07.909396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bd6b0238a2f'
down_revision: Union[str, Sequence[str], None] = '838700396f8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('accumulated', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'accumulated')
    # ### end Alembic commands ###
