"""empty message

Revision ID: a49fc82d7dad
Revises: f3f25ade4918
Create Date: 2026-02-18 22:06:19.689588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49fc82d7dad'
down_revision: Union[str, Sequence[str], None] = 'f3f25ade4918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss_alive',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boss_alive')
    # ### end Alembic commands ###
