"""empty message

Revision ID: f3f25ade4918
Revises: 1c98c2617a89
Create Date: 2026-02-15 23:22:13.948670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f25ade4918'
down_revision: Union[str, Sequence[str], None] = '1c98c2617a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_boss',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('boss_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_boss')
    # ### end Alembic commands ###
